import '../models/money_budget.dart';
import '../models/money_category.dart';
import '../models/money_transaction.dart';
import '../models/recurring_money_transaction.dart';
import '../models/transaction_type.dart';

/// Contract for accessing and manipulating Money data.
abstract class MoneyRepository {
  /// Retrieves all recorded transactions.
  Future<List<MoneyTransaction>> getTransactions();

  /// Retrieves a specific transaction by its unique [id], or null if not found.
  Future<MoneyTransaction?> getTransactionById(String id);

  /// Validates and adds a new transaction.
  Future<MoneyTransaction> addTransaction(MoneyTransaction transaction);

  /// Validates and updates an existing transaction while preserving its ID.
  Future<MoneyTransaction> updateTransaction(MoneyTransaction transaction);

  /// Permanently removes a transaction by its [id].
  /// Returns true if found and removed, false otherwise.
  Future<bool> deleteTransaction(String id);

  /// Retrieves all available categories (both built-in and custom), optionally filtered by [type].
  Future<List<MoneyCategory>> getCategories({TransactionType? type});

  /// Validates and adds a new custom category.
  Future<MoneyCategory> addCategory(MoneyCategory category);

  /// Validates and updates an existing category.
  Future<MoneyCategory> updateCategory(MoneyCategory category);

  /// Validates and deletes a custom category by its [id].
  /// Throws [MoneyValidationException] if attempting to delete a built-in category,
  /// or if the category is currently used by existing transactions or budgets.
  Future<bool> deleteCategory(String id);

  /// Retrieves all recorded budgets, optionally filtered by [year] and/or [month].
  Future<List<MoneyBudget>> getBudgets({int? year, int? month});

  /// Retrieves a specific budget by its unique [id], or null if not found.
  Future<MoneyBudget?> getBudgetById(String id);

  /// Retrieves a specific budget for [categoryId] in [year] and [month], or null if not found.
  Future<MoneyBudget?> getBudgetByCategory({
    required String categoryId,
    required int year,
    required int month,
  });

  /// Validates and adds a new budget.
  Future<MoneyBudget> addBudget(MoneyBudget budget);

  /// Validates and updates an existing budget.
  Future<MoneyBudget> updateBudget(MoneyBudget budget);

  /// Permanently removes a budget by its [id].
  /// Returns true if found and removed, false otherwise.
  Future<bool> deleteBudget(String id);

  /// Retrieves all recurring transaction rules.
  Future<List<RecurringMoneyTransaction>> getRecurringTransactions();

  /// Retrieves a specific recurring transaction rule by its unique [id], or null if not found.
  Future<RecurringMoneyTransaction?> getRecurringById(String id);

  /// Validates and adds a new recurring transaction rule.
  Future<RecurringMoneyTransaction> addRecurring(RecurringMoneyTransaction recurring);

  /// Validates and updates an existing recurring transaction rule while preserving its ID and createdAt.
  Future<RecurringMoneyTransaction> updateRecurring(RecurringMoneyTransaction recurring);

  /// Permanently removes a recurring transaction rule by its [id].
  /// Does NOT delete transactions that were already generated by this rule.
  Future<bool> deleteRecurring(String id);
}
